### ISSUE TITLE
Publish a phet-io version to support the visualization wrapper

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-law#102]
To support https://github.com/phetsims/phet-io-wrapper-visualizing-engagement/issues/9#issuecomment-354510219 we would like to publish a PhET-iO version of Faraday's Law with the fixed size iframe recorder.

I asked on Slack:

> Is there a new “instructions” document like https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md for chipper 2.0?

**Comment by samreid** [comment]
I ran `grunt --brands=phet-io` and tried to test locally and saw this for instance proxies:

![image](https://user-images.githubusercontent.com/679486/34488650-8901fe5c-ef96-11e7-81d8-1bb80db212e1.png)

**Comment by samreid** [comment]
@jonathanolson @mattpen can you please assist?

**Comment by samreid** [comment]
Maybe I should try with chipper 1.0?

**Comment by samreid** [comment]
Same problem.  I'm going to need assistance.

**Comment by samreid** [comment]
Maybe the build assumes the deployment location and cannot be used for local testing?  I tried deploying with `grunt dev --brands=phet-io` and received this error log:

```
~/github/faradays-law$ grunt dev --brands=phet-io
Running "dev" task
(Forwarding task to perennial)
Running "dev" task
info: running [[ -d "/htdocs/physics/phet/dev/html/faradays-law" ]] && echo exists || echo not remotely on spot.colorado.edu
info: running [[ -d "/htdocs/physics/phet/dev/html/faradays-law/1.4.0-dev.11" ]] && echo exists || echo not remotely on spot.colorado.edu
Deploy 1.4.0-dev.11 to spot.colorado.edu [Y/n]?Y
info: Setting version from package.json for faradays-law to 1.4.0-dev.11
info: git add package.json on faradays-law
info: git commit on faradays-law with message:
Bumping version to 1.4.0-dev.11
info: git push on faradays-law to master
info: npm update on faradays-law
info: npm update on chipper
info: building faradays-law
Running "lint-all" task

Running "clean" task

Running "build" task
Building runnable repository (faradays-law, brands: phet-io)
Building brand: phet-io
>> require.js optimization for brand: phet-io complete (3407378 bytes)
>> Minification for phet-io complete
>> Require.js: 1008334 bytes
>> Preloads: 202783 bytes
>> Mipmaps: 700324 bytes

Done.

info: running mkdir -p "/htdocs/physics/phet/dev/html/faradays-law/1.4.0-dev.11" remotely on spot.colorado.edu
info: transferring ../faradays-law/build/* remotely to /htdocs/physics/phet/dev/html/faradays-law/1.4.0-dev.11/ on spot.colorado.edu
Fatal error: Perennial task failed:
Error: scp -r ../faradays-law/build/* REDACTED@spot.colorado.edu:/htdocs/physics/phet/dev/html/faradays-law/1.4.0-dev.11/ in . failed with exit code 1 and stdout:

  at ChildProcess.process.on.code (/Users/samreid/github/perennial/js/common/execute.js:65:17)
  at emitTwo (events.js:125:13)
  at ChildProcess.emit (events.js:213:7)
  at maybeClose (internal/child_process.js:927:16)
  at Socket.stream.socket.on (internal/child_process.js:348:11)
  at emitOne (events.js:115:13)
  at Socket.emit (events.js:210:7)
  at Pipe._handle.close [as _onclose] (net.js:549:12)

Full Error details:
{
  "cmd": "scp",
  "args": [
    "-r",
    "../faradays-law/build/*",
    "REDACTED@spot.colorado.edu:/htdocs/physics/phet/dev/html/faradays-law/1.4.0-dev.11/"
  ],
  "cwd": ".",
  "stdout": "",
  "code": 1
}
Fatal error: perennial grunt "--repo=faradays-law" "dev" "--brands=phet-io" failed with code 1
```

**Comment by samreid** [comment]
Looks like the fail is on the SCP step.  I’ll try a --brands=phet and see if that gives any helpful information.

**Comment by samreid** [comment]
```
~/github/faradays-law$ grunt dev --brands=phet
Running "dev" task
(Forwarding task to perennial)
Running "dev" task
info: running [[ -d "/htdocs/physics/phet/dev/html/faradays-law" ]] && echo exists || echo not remotely on spot.colorado.edu
info: running [[ -d "/htdocs/physics/phet/dev/html/faradays-law/1.4.0-dev.12" ]] && echo exists || echo not remotely on spot.colorado.edu
Deploy 1.4.0-dev.12 to spot.colorado.edu [Y/n]?Y
info: Setting version from package.json for faradays-law to 1.4.0-dev.12
info: git add package.json on faradays-law
info: git commit on faradays-law with message:
Bumping version to 1.4.0-dev.12
info: git push on faradays-law to master
info: npm update on faradays-law
info: npm update on chipper
info: building faradays-law
Running "lint-all" task

Running "clean" task

Running "build" task
Building runnable repository (faradays-law, brands: phet)
Building brand: phet
>> require.js optimization for brand: phet complete (3242700 bytes)
>> Minification for phet complete
>> Require.js: 964847 bytes
>> Preloads: 184733 bytes
>> Mipmaps: 692676 bytes

Done.

info: running mkdir -p "/htdocs/physics/phet/dev/html/faradays-law/1.4.0-dev.12" remotely on spot.colorado.edu
info: transferring ../faradays-law/build/* remotely to /htdocs/physics/phet/dev/html/faradays-law/1.4.0-dev.12/ on spot.colorado.edu
Fatal error: Perennial task failed:
Error: scp -r ../faradays-law/build/* REDACTED@spot.colorado.edu:/htdocs/physics/phet/dev/html/faradays-law/1.4.0-dev.12/ in . failed with exit code 1 and stdout:

  at ChildProcess.process.on.code (/Users/samreid/github/perennial/js/common/execute.js:65:17)
  at emitTwo (events.js:125:13)
  at ChildProcess.emit (events.js:213:7)
  at maybeClose (internal/child_process.js:927:16)
  at Socket.stream.socket.on (internal/child_process.js:348:11)
  at emitOne (events.js:115:13)
  at Socket.emit (events.js:210:7)
  at Pipe._handle.close [as _onclose] (net.js:549:12)

Full Error details:
{
  "cmd": "scp",
  "args": [
    "-r",
    "../faradays-law/build/*",
    "REDACTED@spot.colorado.edu:/htdocs/physics/phet/dev/html/faradays-law/1.4.0-dev.12/"
  ],
  "cwd": ".",
  "stdout": "",
  "code": 1
}
Fatal error: perennial grunt "--repo=faradays-law" "dev" "--brands=phet" failed with code 1
```

**Comment by samreid** [comment]
When I ran the scp command verbatim on the command line, it worked properly.

**Comment by samreid** [comment]
@jonathanolson suggested to use chipper 1.0.  When I did so, I was able to publish and launch the wrapper, but received this error:

https://www.colorado.edu/physics/phet/dev/html/faradays-law/1.4.0-phetiodev.14/wrappers/record/record-1024x618.html?sim=faradays-law&relativeSimPath

"cannot read property phetioID of undefined"

**Comment by samreid** [comment]
OK I published a sim here: https://www.colorado.edu/physics/phet/dev/html/faradays-law/1.4.0-phetiodev.15/wrappers/record/record-1024x618.html . We should be able to use local file recording or metacog recording for this one.  May need a new metacog account or widget.

**Comment by samreid** [comment]
I'm still running into numerous problems with the chipper 2.0 deploys.  I'm wondering if I should try to deploy the playback/visualization wrapper with 1.0 or keep trying to figure out 2.0.  Tagging @ariel-phet for advice.

**Comment by samreid** [comment]
> figure out 2.0

should say "get 2.0 working"

**Comment by jonathanolson** [comment]
I'm available to collaborate to help resolve these issues (would be good to do before merging ideally).

**Comment by samreid** [comment]
I worked through a few problems in the wrapper side and it seems all is well now, at least dev versions can be built and deployed without issues.  Also, we have switched to Capacitor Lab: Basics for this initial version, so I'll close this one.
