### ISSUE TITLE
CT converting circular structure to JSON

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-law#170]
```
aradays-law : build
Build failed with status code 3:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (faradays-law, brands: phet, phet-io)
Building brand: phet
Fatal error: Converting circular structure to JSON

Webpack build errors: [ ModuleNotFoundError: Module not found: Error: Can't resolve '../../../../tambo/js/shared-sound-players/boundaryReachedSoundPlayer.js' in '/data/share/phet/continuous-testing/ct-snapshots/1596722042927/faradays-law/js/faradays-law/view'
at factory.create (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/lib/Compilation.js:925:10)
at factory (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
at resolver (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
at asyncLib.parallel (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
at /data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/neo-async/async.js:2830:7
at /data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/neo-async/async.js:6877:13
at normalResolver.resolve (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
at doResolve (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn0 (<anonymous>:15:1)
at resolver.doResolve (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn0 (<anonymous>:15:1)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn0 (<anonymous>:27:1)
at resolver.doResolve (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn42 (<anonymous>:16:1)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn0 (<anonymous>:27:1)
at resolver.doResolve (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn1 (<anonymous>:16:1)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn0 (<anonymous>:15:1)
at fs.stat (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15)
at process.nextTick (/data/share/phet/continuous-testing/ct-snapshots/1596722042927/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15)
at process._tickCallback (internal/process/next_tick.js:61:11)

resolve '../../../../tambo/js/shared-sound-players/boundaryReachedSoundPlayer.js' in '/data/share/phet/continuous-testing/ct-snapshots/1596722042927/faradays-law/js/faradays-law/view'
using description file: /data/share/phet/continuous-testing/ct-snapshots/1596722042927/faradays-law/package.json (relative path: ./js/faradays-law/view)
Field 'browser' doesn't contain a valid alias configuration
using description file: /data/share/phet/continuous-testing/ct-snapshots/1596722042927/tambo/package.json (relative path: ./js/shared-sound-players/boundaryReachedSoundPlayer.js)
no extension
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1596722042927/tambo/js/shared-sound-players/boundaryReachedSoundPlayer.js doesn't exist
.wasm
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1596722042927/tambo/js/shared-sound-players/boundaryReachedSoundPlayer.js.wasm doesn't exist
.mjs
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1596722042927/tambo/js/shared-sound-players/boundaryReachedSoundPlayer.js.mjs doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1596722042927/tambo/js/shared-sound-players/boundaryReachedSoundPlayer.js.js doesn't exist
.json
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1596722042927/tambo/js/shared-sound-players/boundaryReachedSoundPlayer.js.json doesn't exist
as directory
/data/share/phet/continuous-testing/ct-snapshots/1596722042927/tambo/js/shared-sound-players/boundaryReachedSoundPlayer.js doesn't exist ]
Snapshot from 8/6/2020, 7:54:02 AM

----------------------------------

faradays-law : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596722042927/phet-io-wrappers/phet-io-wrappers-tests.html?sim=faradays-law
1 out of 1 tests passed. 0 failed.

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 8/6/2020, 7:54:02 AM
```

**Comment by jbphet** [comment]
Fixed, closing.
