### ISSUE TITLE
CT get magnet edge notification failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-law#172]
```
faradays-law : top-level-unit-tests : unbuilt?ea&brand=phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597313842663/faradays-law/faradays-law-tests.html?ea&brand=phet-io
3 out of 4 tests passed. 1 failed.
MagnetRegionManager: get magnet edge notification failed:
Died on test #1 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597313842663/faradays-law/js/faradays-law/view/MagnetRegionsTests.js:103:1: Assertion failed: phetioID already registered: faradaysLaw.general.model.topCoilVisibleProperty
Error: Assertion failed: phetioID already registered: faradaysLaw.general.model.topCoilVisibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597313842663/assert/js/assert.js:22:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597313842663/phet-io/js/phetioEngine.js:426:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597313842663/phet-io/js/phetioEngine.js:625:49)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597313842663/tandem/js/Tandem.js:166:38)
at BooleanProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597313842663/tandem/js/PhetioObject.js:344:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597313842663/tandem/js/PhetioObject.js:189:10)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597313842663/axon/js/Property.js:69:5)
at new BooleanProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597313842663/axon/js/BooleanProperty.js:45:5)
at new FaradaysLawModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597313842663/faradays-law/js/faradays-law/model/FaradaysLawModel.js:48:33)
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597313842663/faradays-law/js/faradays-law/view/MagnetRegionsTests.js:105:17)

id: Bayes Chrome
Snapshot from 8/13/2020, 4:17:22 AM
```

**Comment by jbphet** [comment]
This appears to be a failure of the unit tests associated with the `MagnetRegionManager`.  I can't seem to duplicate it locally, and I don't know what it is indicating.  @jessegreenberg - `MagnetRegionManager` is part of the a11y support, and I believe you're picking up the a11y mantle for this sim.  Can you please take a look?  If nothing else, you could always just get rid of the test that's failing.  I was just reluctant to do that in case it was useful.

**Comment by jessegreenberg** [comment]
Thanks @jbphet - the assertion is
> Died on test #1 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597434192233/faradays-law/js/faradays-law/view/MagnetRegionsTests.js:103:1: Assertion failed: phetioID already registered: faradaysLaw.general.model.topCoilVisibleProperty
Error: Assertion failed: phetioID already registered: faradaysLaw.general.model.topCoilVisibleProperty

I think it is because tests create more than one FaradaysLawModel, perhaps without cleaning it up/disposing? Maybe we can use one model for all tests. I am able to duplicate the problem by running unit tests with `brand=phet-io` query param.

**Comment by jessegreenberg** [comment]
OK, should be fixed after the above commit.
