### ISSUE TITLE
CT if we hit this something is wrong in the code above

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-law#204]
```
faradays-law : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/faradays-law/faradays-law_en.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1606796277994%22%2C%22timestamp%22%3A1606814627216%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: if we hit this, something is wrong in the code above
Error: Assertion failed: if we hit this, something is wrong in the code above
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/assert/js/assert.js:25:13)
at FaradaysLawModel.checkObjectMotion (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/faradays-law/js/faradays-law/model/FaradaysLawModel.js:278:17)
at FaradaysLawModel.moveMagnetToPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/faradays-law/js/faradays-law/model/FaradaysLawModel.js:415:41)
at DragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/faradays-law/js/faradays-law/view/MagnetNodeWithField.js:132:15)
at DragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/scenery/js/listeners/PressListener.js:432:10)
at DragListener._dragAction.Action.parameters.name (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/scenery/js/listeners/DragListener.js:244:36)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/axon/js/Action.js:225:18)
at DragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/scenery/js/listeners/DragListener.js:363:22)
at DragListener.pointerMove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/scenery/js/listeners/PressListener.js:790:14)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/scenery/js/input/Input.js:1822:25)
id: Bayes Chrome
Snapshot from 11/30/2020, 9:17:57 PM

----------------------------------

faradays-law : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/faradays-law/faradays-law_en.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1606796277994%22%2C%22timestamp%22%3A1606830728591%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: if we hit this, something is wrong in the code above
Error: Assertion failed: if we hit this, something is wrong in the code above
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/assert/js/assert.js:25:13)
at FaradaysLawModel.checkObjectMotion (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/faradays-law/js/faradays-law/model/FaradaysLawModel.js:249:17)
at FaradaysLawModel.moveMagnetToPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/faradays-law/js/faradays-law/model/FaradaysLawModel.js:415:41)
at FaradaysLawKeyboardDragListener.drag [as _drag] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/faradays-law/js/faradays-law/view/FaradaysLawKeyboardDragListener.js:23:13)
at FaradaysLawKeyboardDragListener.updatePosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/scenery/js/listeners/KeyboardDragListener.js:574:16)
at FaradaysLawKeyboardDragListener.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/scenery/js/listeners/KeyboardDragListener.js:448:14)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/axon/js/TinyEmitter.js:85:42)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/joist/js/Sim.js:278:17
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/axon/js/Action.js:225:18)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/joist/js/Sim.js:1026:31)
id: Bayes Chrome
Snapshot from 11/30/2020, 9:17:57 PM

----------------------------------

faradays-law : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/faradays-law/faradays-law_en.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1606796277994%22%2C%22timestamp%22%3A1606801819447%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: if we hit this, something is wrong in the code above
Error: Assertion failed: if we hit this, something is wrong in the code above
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/assert/js/assert.js:25:13)
at FaradaysLawModel.checkObjectMotion (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/faradays-law/js/faradays-law/model/FaradaysLawModel.js:249:17)
at FaradaysLawModel.moveMagnetToPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/faradays-law/js/faradays-law/model/FaradaysLawModel.js:415:41)
at DragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/faradays-law/js/faradays-law/view/MagnetNodeWithField.js:132:15)
at DragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/scenery/js/listeners/PressListener.js:432:10)
at DragListener._dragAction.Action.parameters.name (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/scenery/js/listeners/DragListener.js:244:36)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/axon/js/Action.js:225:18)
at DragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/scenery/js/listeners/DragListener.js:363:22)
at DragListener.pointerMove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/scenery/js/listeners/PressListener.js:790:14)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1606796277994/scenery/js/input/Input.js:1822:25)
id: Bayes Chrome
Snapshot from 11/30/2020, 9:17:57 P
```

**Comment by jbphet** [comment]
This was introduced when I removed the minimum distance to boundaries yesterday, and comes up when one of the translation values, x or y, is zero and the other isn't.  I've committed a fix.  Closing.
