### ISSUE TITLE
CT should not be in this state when moving right

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-law#213]
```
faradays-law : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/faradays-law_en.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1608008155855%22%2C%22timestamp%22%3A1608010594413%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should not be in this state when moving right
Error: Assertion failed: should not be in this state when moving right
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/assert/js/assert.js:25:13)
at updateSlideTarget (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:119:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:158:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:280:25)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:178:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/sun/js/buttons/RectangularRadioButton.js:126:51
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/14/2020, 9:55:55 PM

----------------------------------

faradays-law : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/faradays-law_en.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1608008155855%22%2C%22timestamp%22%3A1608023946582%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should not be in this state when moving right
Error: Assertion failed: should not be in this state when moving right
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/assert/js/assert.js:25:13)
at updateSlideTarget (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:119:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:158:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:280:25)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:178:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/sun/js/buttons/RectangularRadioButton.js:126:51
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/14/2020, 9:55:55 PM

----------------------------------

faradays-law : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/faradays-law_en.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1608008155855%22%2C%22timestamp%22%3A1608021105028%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should not be in this state when moving left
Error: Assertion failed: should not be in this state when moving left
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/assert/js/assert.js:25:13)
at updateSlideTarget (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:133:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:158:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:280:25)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:178:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/sun/js/buttons/RectangularRadioButton.js:126:51
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/14/2020, 9:55:55 PM

----------------------------------

faradays-law : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/faradays-law_en.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1608008155855%22%2C%22timestamp%22%3A1608011335895%7D&brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: should not be in this state when moving right
Error: Assertion failed: should not be in this state when moving right
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/assert/js/assert.js:25:13)
at updateSlideTarget (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:119:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:158:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:280:25)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:178:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/sun/js/buttons/RectangularRadioButton.js:126:51
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/14/2020, 9:55:55 PM

----------------------------------

faradays-law : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/faradays-law_en.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1608008155855%22%2C%22timestamp%22%3A1608024936318%7D&brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: should not be in this state when moving right
Error: Assertion failed: should not be in this state when moving right
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/assert/js/assert.js:25:13)
at updateSlideTarget (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:119:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:158:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:280:25)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:178:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/sun/js/buttons/RectangularRadioButton.js:126:51
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/14/2020, 9:55:55 PM

----------------------------------

faradays-law : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/faradays-law_en.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1608008155855%22%2C%22timestamp%22%3A1608012212843%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should not be in this state when moving left
Error: Assertion failed: should not be in this state when moving left
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/assert/js/assert.js:25:13)
at updateSlideTarget (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:133:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:158:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:280:25)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:178:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/sun/js/buttons/RectangularRadioButton.js:126:51
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/14/2020, 9:55:55 PM

----------------------------------

faradays-law : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/faradays-law_en.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1608008155855%22%2C%22timestamp%22%3A1608023612515%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: should not be in this state when moving right
Error: Assertion failed: should not be in this state when moving right
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/assert/js/assert.js:25:13)
at updateSlideTarget (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:119:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:158:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:280:25)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:178:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/sun/js/buttons/RectangularRadioButton.js:126:51
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/14/2020, 9:55:55 PM

----------------------------------

faradays-law : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/phet-io-wrappers/mirror-inputs/?sim=faradays-law&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1608008155855%22%2C%22timestamp%22%3A1608010328936%7D
Uncaught Error: Uncaught Error: Assertion failed: should not be in this state when moving left
Error: Assertion failed: should not be in this state when moving left
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/assert/js/assert.js:25:13)
at updateSlideTarget (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:133:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:158:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:280:25)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:178:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/sun/js/buttons/RectangularRadioButton.js:126:51
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/14/2020, 9:55:55 PM

----------------------------------

faradays-law : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/phet-io-wrappers/mirror-inputs/?sim=faradays-law&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1608008155855%22%2C%22timestamp%22%3A1608023505974%7D
Uncaught Error: Uncaught Error: Assertion failed: should not be in this state when moving right
Error: Assertion failed: should not be in this state when moving right
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/assert/js/assert.js:25:13)
at updateSlideTarget (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:119:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:158:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:280:25)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:178:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/sun/js/buttons/RectangularRadioButton.js:126:51
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/14/2020, 9:55:55 PM

----------------------------------

faradays-law : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/phet-io-wrappers/state/?sim=faradays-law&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1608008155855%22%2C%22timestamp%22%3A1608012163302%7D
Uncaught Error: Uncaught Error: Assertion failed: should not be in this state when moving left
Error: Assertion failed: should not be in this state when moving left
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/assert/js/assert.js:25:13)
at updateSlideTarget (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:133:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:158:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:280:25)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:178:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/sun/js/buttons/RectangularRadioButton.js:126:51
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/14/2020, 9:55:55 PM

----------------------------------

faradays-law : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/phet-io-wrappers/state/?sim=faradays-law&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1608008155855%22%2C%22timestamp%22%3A1608023525747%7D
Uncaught Error: Uncaught Error: Assertion failed: should not be in this state when moving left
Error: Assertion failed: should not be in this state when moving left
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/assert/js/assert.js:25:13)
at updateSlideTarget (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:133:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:158:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:280:25)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:178:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/sun/js/buttons/RectangularRadioButton.js:126:51
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/14/2020, 9:55:55 PM

----------------------------------

faradays-law : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/studio/?sim=faradays-law&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1608008155855%22%2C%22timestamp%22%3A1608010494034%7D
Uncaught Error: Uncaught Error: Assertion failed: should not be in this state when moving right
Error: Assertion failed: should not be in this state when moving right
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/assert/js/assert.js:25:13)
at updateSlideTarget (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:119:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:158:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:280:25)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:178:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/sun/js/buttons/RectangularRadioButton.js:126:51
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/14/2020, 9:55:55 PM

----------------------------------

faradays-law : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/studio/?sim=faradays-law&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1608008155855%22%2C%22timestamp%22%3A1608023553370%7D
Uncaught Error: Uncaught Error: Assertion failed: should not be in this state when moving right
Error: Assertion failed: should not be in this state when moving right
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/assert/js/assert.js:25:13)
at updateSlideTarget (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:119:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:158:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:280:25)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:178:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/sun/js/buttons/RectangularRadioButton.js:126:51
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/14/2020, 9:55:55 PM

----------------------------------

faradays-law : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/faradays-law_en.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1608008155855%22%2C%22timestamp%22%3A1608009461768%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: should not be in this state when moving left
Error: Assertion failed: should not be in this state when moving left
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/assert/js/assert.js:25:13)
at updateSlideTarget (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:133:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:158:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:280:25)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:178:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/sun/js/buttons/RectangularRadioButton.js:126:51
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/14/2020, 9:55:55 PM

----------------------------------

faradays-law : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/faradays-law_en.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1608008155855%22%2C%22timestamp%22%3A1608024310241%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: should not be in this state when moving right
Error: Assertion failed: should not be in this state when moving right
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/assert/js/assert.js:25:13)
at updateSlideTarget (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:119:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:158:7
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:280:25)
at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Property.js:178:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/sun/js/buttons/RectangularRadioButton.js:126:51
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608008155855/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/14/2020, 9:55:55 PM
```

**Comment by jbphet** [comment]
Fixed.  This was due to a change made to how the auto-slide animation responded to the coil-change configuration, and I have simplified things so that any in-progress animation that is occurring when the coil change configuration changes is stopped.  Closing.
