### ISSUE TITLE
CT t.domEvent.getModifierState is not a function

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-law#216]
```
faradays-law : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608612331446%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: t.domEvent.getModifierState is not a function
TypeError: t.domEvent.getModifierState is not a function
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608612331446%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:1723230
at Array.forEach (<anonymous>)
at PS.keydown (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608612331446%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:1723202)
at Vo.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608612331446%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:507187)
at Vo.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608612331446%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:507362)
at Vo.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608612331446%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:506952)
at Vo.dispatchA11yEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608612331446%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:503480)
at Vo.keydownAction.W.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608612331446%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:500422)
at N.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608612331446%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:53815)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608612331446%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:501132)
id: Bayes Chrome
Snapshot from 12/21/2020, 9:14:29 PM

----------------------------------

faradays-law : interactive-description-fuzzBoard : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608629626423%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: t.domEvent.getModifierState is not a function
TypeError: t.domEvent.getModifierState is not a function
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608629626423%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:1723230
at Array.forEach (<anonymous>)
at PS.keydown (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608629626423%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:1723202)
at Vo.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608629626423%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:507187)
at Vo.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608629626423%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:507362)
at Vo.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608629626423%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:506952)
at Vo.dispatchA11yEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608629626423%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:503480)
at Vo.keydownAction.W.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608629626423%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:500422)
at N.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608629626423%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:53815)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/build/phet/faradays-law_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608629626423%7D&fuzzBoard&supportsDescriptions&memoryLimit=1000:807:501132)
id: Bayes Chrome
Snapshot from 12/21/2020, 9:14:29 PM

----------------------------------

faradays-law : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/faradays-law_en.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608611870105%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: event.domEvent.getModifierState is not a function
TypeError: event.domEvent.getModifierState is not a function
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:168:53
at Array.forEach (<anonymous>)
at MagnetAutoSlideKeyboardListener.keydown (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:167:25)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/scenery/js/input/Input.js:1819:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/scenery/js/input/Input.js:1851:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/scenery/js/input/Input.js:1777:10)
at Input.dispatchA11yEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/scenery/js/input/Input.js:1052:12)
at Input.keydownAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/scenery/js/input/Input.js:706:14)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/axon/js/Action.js:225:18)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/scenery/js/input/Input.js:754:30)
id: Bayes Chrome
Snapshot from 12/21/2020, 9:14:29 PM

----------------------------------

faradays-law : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/faradays-law_en.html?continuousTest=%7B%22test%22%3A%5B%22faradays-law%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1608610469765%22%2C%22timestamp%22%3A1608627858811%7D&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: event.domEvent.getModifierState is not a function
TypeError: event.domEvent.getModifierState is not a function
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:168:53
at Array.forEach (<anonymous>)
at MagnetAutoSlideKeyboardListener.keydown (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/faradays-law/js/faradays-law/view/MagnetAutoSlideKeyboardListener.js:167:25)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/scenery/js/input/Input.js:1819:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/scenery/js/input/Input.js:1851:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/scenery/js/input/Input.js:1777:10)
at Input.dispatchA11yEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/scenery/js/input/Input.js:1052:12)
at Input.keydownAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/scenery/js/input/Input.js:706:14)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/axon/js/Action.js:225:18)
at HTMLDivElement.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608610469765/scenery/js/input/Input.js:754:30)
id: Bayes Chrome
Snapshot from 12/21/2020, 9:14:29 PM
```

**Comment by jbphet** [comment]
This can be duplicated by running with the `fuzzBoard` flag.

**Comment by jbphet** [comment]
I think that this is a problem with the test, not the simulation code.  I'll log an issue for further investigation.

**Comment by KatieWoe** [comment]
Used fuzzBoard on rc.4 and didn't see this error. Closing for now. Will reopen if something comes up.
